PROJECTS = [
    {
        "id": "companion",
        "name": "Majin Companion",
        "icon": "🔥",
        "path": r"D:\Majin Companion",
        "url": None,
        "status": "Building Yuri's personal OS.",
        "color": "purple",
        "priority": 0,
        "momentum": 95,
    },
    {
        "id": "rig",
        "name": "Majin Rig MK1",
        "icon": "🛠️",
        "path": r"D:\MAJIN RIG MK-1",
        "url": None,
        "status": "Designing the sim rig platform.",
        "color": "green",
        "priority": 1,
        "momentum": 80,
    },
    {
        "id": "garage",
        "name": "Majin Garage",
        "icon": "🚗",
        "path": r"C:\Users\Tora\EJ6-hub\ej6-garage",
        "url": "https://ej6-garage-main-pe5bqi.laravel.cloud/",
        "status": "Maintenance & upgrades.",
        "color": "purple",
        "priority": 2,
        "momentum": 45,
    },
    {
        "id": "riftlab",
        "name": "RiftLab",
        "icon": "🥊",
        "path": r"C:\Users\Tora\Documents\DBFZ TEAM BUILDER",
        "url": "https://riftlab.pages.dev/",
        "status": "FG knowledge system.",
        "color": "green",
        "priority": 3,
        "momentum": 60,
    },
    {
        "id": "portfolio",
        "name": "Majin Portfolio",
        "icon": "🌐",
        "path": r"C:\Users\Tora\Documents\portfoliooo\MainHub",
        "url": "https://mainhub-5bg.pages.dev/#home",
        "status": "Show the world.",
        "color": "purple",
        "priority": 4,
        "momentum": 35,
    },
    {
        "id": "leaderboard",
        "name": "Homies Leaderboard",
        "icon": "🏆",
        "path": r"C:\Users\Tora\leaderboard-hub",
        "url": "https://backfishracers.up.railway.app/",
        "status": "Community racing.",
        "color": "green",
        "priority": 5,
        "momentum": 30,
    },
]